### ISSUE TITLE
error when run on schedule

### ISSUE THREAD

**Issue by Lupraxus** [magnetikonline/action-slack-workflow-start-finish#1]
I use this action fine with pushes, pull requests etc however I created a nightly scheduled based job and it failed.

Error: Cannot read property 'full_name' of undefined

The only reference I can find to this being used is:

https://github.com/magnetikonline/action-slack-workflow-start-finish/blob/a88cf377629000192291252be005f6b0b46b19ec/src/lib.js#L21

**Comment by magnetikonline** [comment]
Thanks @TGWolf for the issue. That does seem _really weird_ this part of the payload isn't present in scheduled workflow jobs - as it can very much be tied to a repository.

Let me test this myself and POC - see if there is a more defensive way and/or another way to get the repository name from scheduled workflow runs.

**Comment by Lupraxus** [comment]
@magnetikonline I am pretty new to actions to be honest, but could you use the github context of github.repository or similar instead?

**Comment by magnetikonline** [comment]
@TGWolf that's what I'm using - but the event payload passed to the different event types (`pull-request` / `push` / etc.) can vary - which I'm guessing is the case here.

I'll find some time to dig into the payload offered up by a scheduled run. See what's possible.

**Comment by Lupraxus** [comment]
@magnetikonline ah yeah sorry my bad, like I say still new to actions (only started playing with them last week and ditching travis). I can see in main.js you are passing the complete github context in and using that later in lib.js

**Comment by magnetikonline** [comment]
All good - just giving some background context. 👍 😄 .

**Comment by magnetikonline** [comment]
Hey @TGWolf - just circling back on this. I've submitted the issue to https://github.community/t/scheduled-github-action-workflow-runs-not-include-a-full-event-payload/260053.

- But it turns out I can get this information in another method/way via the [GitHub NPM module `get()` function](https://github.com/actions/toolkit/blob/c5278cdd088a8ed6a87dbd5c80d7c1ae03beb6e5/packages/github/src/context.ts#L64-L81) - so I'm gonna code that up. 👍
- Or even easier - just use [`github.repository`](https://github.com/actions/checkout/blob/2541b1294d2704b0964813337f33b291d3f8596b/action.yml#L4-L6) as an input.

Also want to make use of [`this.serverUrl`](https://github.com/actions/toolkit/blob/c5278cdd088a8ed6a87dbd5c80d7c1ae03beb6e5/packages/github/src/context.ts#L50) to resolve `https://github.com` 👍

**Comment by magnetikonline** [comment]
Now fixed via 199858c2cb96c5df43efc15ec8744c929d9e9855, 1c0408b82ade9a92e0146c3ff057be17a68706ff, abe09b0ac09a2f2826cf9df04c90b1a459ebc492.
